services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: "/app/python_src"
    # command: ['rye', 'run', 'uvicorn', 'config.asgi:application', '--host', '0.0.0.0', '--port', '8000']
    command: ['/app/scripts/run.sh']
    # tty: true