services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./python_src:/app/python_src
    working_dir: "/app/python_src"
    command: ['rye', 'run', 'uvicorn', 'config.asgi:application', '--host', '0.0.0.0', '--port', '8000']
