services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: "/app/"
    command: ["./scripts/run.sh"]
    # tty: true